# Generated by Django 5.2.8 on 2025-11-13 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reagents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome do Reagente"),
                ),
                ("mark", models.CharField(max_length=50, verbose_name="Marca")),
                ("quantity", models.IntegerField(default=0, verbose_name="Quantidade")),
                (
                    "unity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("g", "g"),
                            ("mL", "mL"),
                            ("kit", "kit"),
                            ("kg", "kg"),
                            ("un.", "un."),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Unidade",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Validade"
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        default="-", max_length=50, verbose_name="Localizacao"
                    ),
                ),
                (
                    "rack",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Prateleira"
                    ),
                ),
                (
                    "verify",
                    models.DateTimeField(auto_now=True, verbose_name="Verificacao"),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True, default="-", max_length=50, verbose_name="Setor"
                    ),
                ),
                (
                    "users",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reagente",
                "ordering": ["name"],
            },
        ),
    ]
